# https://doc.mergify.io/examples.html#imgbot
pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
