language: python
python:
  - "2.7"

# cache: pip

install:
  - pip install -r requirements.txt

branches:
  only:
  - release

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target-branch: master
  on:
    branch: release
