# Cache Dependencies
cache: pip

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target-branch: master
  on:
    branch: release
