language: python
python:
  - 2.7

branches:
  only:
  - release

install:
  - pip install -r requirements.txt

script:
  - make publish

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: output
  fqdn: karpoke.ignaciocano.com
  skip_cleanup: true
  keep_history: true
  target-branch: master
  on:
    branch: release
  verbose: true
